[font]
size = 11
builtin_box_drawing = false
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "GeistMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "GeistMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "GeistMono Nerd Font"
style = "SemiBold Italic"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#252530"
foreground = "#e0def4"

[window]
opacity = 0.7
blur = true
decorations = "none"
startup_mode = "Maximized"
dimensions = { columns = 5000, lines = 5000 }

[cursor]
style = { shape = "Block" }

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
  { key = "Return", mods = "Control", action = "None" },
]

